### create stremaer 

POST  http://localhost:5000/streamers
Content-Type: application/json

{
    "name": "test2",
    "platfromType": "Twitch",
    "description": "desc1111111desc22222"
}
### get list of streamers

GET http://localhost:5000/streamers
### get streamer
GET http://localhost:5000/streamers/100
### vote streamer +

PUT http://localhost:5000/streamers/1?vote=upvote

### vote streamer -
PUT http://localhost:5000/streamers/1?vote=downvote